### ISSUE TITLE
Release metadata cli no-prompt

### ISSUE THREAD

**Issue by vzhang03** [jspsych/metadata#24]
One idea would be to release it as a flag, so that instead of calling `npx metadata-cli`, you can do something similar to the verbose flag `npx metadata-cli --verbose` and instead do `npx metadata-cli --no-prompt /path/to/data/dir /path/to/metadata-options.json`.

Advantages would be that this would be bundled along with the metadata-cli and the usage of flag allows make it the more advanced choice. This seems like it would also make it easy to deploy and test.

The only disadvantage is that it seems a bit clunky, but separating it into two calls (one to npx package, and second to pass in paths) seems to go against the no-prompt philosophy of it.

**Comment by jodeleeuw** [comment]
I like this approach. What about making something like:

```terminal
npx @jspsych/metadata-cli --data-dir /path/to/data/dir --metadata-options /path/to/metadata-options.json
```
And then if you leave off one of these you get prompted for it in the walkthrough?

**Comment by vzhang03** [comment]
Under this approach would the no-prompt approach become more integrated with the prompted approach and instead become a way of skipping prompting steps. As opposed to being a separate process where the CLI takes in data files and generates a metadata file without creating the directory structure?

If yes, I think this structure sounds good and I think it has the advantage of 1. being done in the terminal so possible with autocomplete 2. doesn't skip the most advantageous parts of using the CLI (Psych-DS generating directory structure). The only thing is that it will likely still prompt for existing metadata seems unavoidable but not like a big deal.  

To get around this we could add another flag such as `--metadata-dir /path/to/metadata/dir` and have the CLI generate a directory if it exists and skip if it already exists. This way we could skip the first prompt as well.

**Comment by jodeleeuw** [comment]
> Under this approach would the no-prompt approach become more integrated with the prompted approach and instead become a way of skipping prompting steps. As opposed to being a separate process where the CLI takes in data files and generates a metadata file without creating the directory structure?

Yeah exactly 👍
